// Throw, and Try...Catch...Finally
// let x = 10;
// if(x==9)
// {
//     try{
//         let e = "This is not correct input";
//      console.log(e);
//     }
//     catch(err){
//         err.e;
//     }
// }
// else{
//     console.log("good Work")
// }